#This is not source code.
#This file exists for packaging releases, and is not source code to mess with.
#Do not edit this file, and do not place anything another file will import here, as it will be wiped on release/update.

#Import stuff we need
import random

#questions class from content.py, since we need to give one file.
class questions():
    class multi_choice():
        test_question = {   #This is a test question, should not appear anywhere in use, just leftover dummy content
            "question":"Test Question?",
            "wrong_answers":["Wrong Answer 1", "Wrong Answer 2", "Wrong Answer 3"],
            "correct_answer":"Correct Answer"
        }
        class normal_questions():
            question1 = {
                "question": "What is an example of Unsupervised learning?",
                "wrong_answers": ["Filtering emails","Diagnosing conditions","Loan Approval prediction"],
                "correct_answer": "Video Game Recommendation"
            }
            question2 = {
                "question": "What is the difference between supervised and unsupervised learning?",
                "wrong_answers": ["Unsupervised uses labeled data to predict", "Both are the same", "Supervised clusters data"],
                "correct_answer":"Supervised uses labeled data"
            }
        class trick_questions():
            question1 = {
                "question": "What year was the first turing test? 1961, 1965, 1969, or 1963?",
                "wrong_answers": ["1961","1965","1969","1963"],
                "correct_answer": "1950"
                }
    class written_answer():
        test_question = { #This is a test question, should not appear anywhere in use, just leftover dummy content
            "question":"Test written question? answer is test",
            "correct_answers":["test"]
        }

#functions from functions.py, again same reason everything from content is here.
def ask_multi_choice(question_dir=dir):
    """
    ask a multi choice question from content.py, but when finished will just pull from within main.py
    input question dir should be like "normal_questions.question1"
    returns if user got question right, and answer they picked in list: [right=bool, answer=str]
    """
    zequestion = eval("questions.multi_choice."+question_dir)
    print(zequestion["question"])
    counter = 1
    choices = []
    for i in zequestion["wrong_answers"]:
        choices.append(i)
    choices.append(zequestion["correct_answer"])
    random.shuffle(choices)
    for i in range(len(choices)):
        print(f"{counter}. {choices[i]}")
        counter += 1

    # loop until we get a valid numeric response
    while True:
        try:
            answer = int(input("Answer (number as shown): "))-1
            if 0 <= answer < len(choices):
                break
            else:
                print("Please enter a number corresponding to one of the choices.")
        except ValueError:
            print("Invalid input; please enter a number.")

    if answer == choices.index(zequestion["correct_answer"]):
        print("Correct!")
        return [True, choices[answer]]
    else:
        print("Wrong!")
        return [False, choices[answer], zequestion["correct_answer"]]
def ask_written(question_dir=dir):
    """
    ask a written question from content.py, but when finished will just pull from within main.py
    input question dir should be like "normal_questions.question1"
    returns if user got question right, and answer they picked in list: [right=bool, answer=str]
    """
    zequestion = eval("questions.written_answer."+question_dir)
    print(zequestion["question"])
    answer = input("<Answer> =  ")
    if answer.lower().strip() == zequestion["correct_answer"].lower().strip():
        print("Right.")
        return [True, answer]
    else:
        print("Wrong.")
        return [False, answer, zequestion["correct_answer"]]

#main_alt.py is pasted here, testing purposes.
done_ids = []
print("This script tests a multi choice and written question.")
#grab a random multi choice that hasnt been done
# only consider attributes that actually contain question dictionaries
valid = [k for k,v in questions.multi_choice.normal_questions.__dict__.items()
         if isinstance(v, dict) and not k.startswith("__")]
while True:
    question = random.choice(valid)
    if question not in done_ids:
        ask_multi_choice(questions.multi_choice.normal_questions.__dict__[question])
        done_ids.append(question)
        break
